# Generated by Django 5.0.4 on 2024-04-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_tblusers_password_tblusers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblusers',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
